trigger:
  - main
  - develop

pool:
  vmImage: 'ubuntu-latest'

variables:
  MAVEN_CACHE_FOLDER: $(Pipeline.Workspace)/.m2/repository
  MAVEN_OPTS: '-Dmaven.repo.local=$(MAVEN_CACHE_FOLDER)'

stages:
  - stage: LighthousePerformanceTests
    displayName: 'Lighthouse Performance Testing'
    jobs:
      - job: RunLighthouseTests
        displayName: 'Run Lighthouse Performance Tests'
        timeoutInMinutes: 30
        steps:
          # Install Node.js
          - task: NodeTool@0
            displayName: 'Install Node.js'
            inputs:
              versionSpec: '18.x'

          # Install Lighthouse CLI
          - script: |
              npm install -g lighthouse
              lighthouse --version
            displayName: 'Install Lighthouse CLI'

          # Install Chrome Browser
          - script: |
              wget -q -O - https://dl.google.com/linux/linux_signing_key.pub | sudo apt-key add - 
              sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
              sudo apt-get update
              sudo apt-get install -y google-chrome-stable
              google-chrome --version
            displayName: 'Install Chrome Browser'

          # Install Java 17
          - task: JavaToolInstaller@0
            displayName: 'Install Java 17'
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'

          # Cache Maven Dependencies
          - task: Cache@2
            displayName: 'Cache Maven Dependencies'
            inputs:
              key: 'maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
                maven
              path: $(MAVEN_CACHE_FOLDER)

          # Download Maven Dependencies
          - task: Maven@4
            displayName: 'Download Maven Dependencies'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'dependency:resolve'
              options: '$(MAVEN_OPTS)'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'

          # Run TestNG Tests
          - task: Maven@4
            displayName: 'Run Lighthouse Performance Tests'
            inputs:
              mavenPomFile: 'pom.xml'
              goals: 'clean test'
              options: '-DsuiteXmlFile=testng.xml -Dallure.results.directory=$(Build.SourcesDirectory)/target/allure-results'
              javaHomeOption: 'JDKVersion'
              jdkVersionOption: '1.17'

          # Create Allure Results Directory (if it doesn't exist)
          - script: |
              mkdir -p $(Build.SourcesDirectory)/target/allure-results
              chmod 755 $(Build.SourcesDirectory)/target/allure-results
            displayName: 'Create Allure Results Directory'

          # Generate Allure Report
          - script: |
              allure generate $(Build.SourcesDirectory)/target/allure-results --clean -o $(Build.ArtifactStagingDirectory)/allure-results
            displayName: 'Generate Allure Report'

          # Publish Allure Report as Artifact
          - task: PublishBuildArtifacts@1
            displayName: 'Publish Allure Report Artifact'
            inputs:
              pathToPublish: '$(Build.ArtifactStagingDirectory)/allure-results'
              artifactName: 'allure-reports'
              publishLocation: 'Container'
